# Generated by Django 4.2.23 on 2025-08-21 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={'ordering': ['created_at']},
        ),
    ]
